/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './component/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        cormorant: ['var(--font-cormorant)', 'Cormorant Garamond', 'Georgia', 'serif'],
        sans:      ['var(--font-inter)',      'Inter', 'system-ui', 'sans-serif'],
        mono:      ['var(--font-geist-mono)', 'monospace'],
      },
      colors: {
        brand: {
          bg:      '#121212',
          dark:    '#1A1A1A',
          card:    '#222222',
          border:  '#333333',
          hover:   '#2A2A2A',
          silver:  '#D4D4D4',
          silver2: '#E0E0E0',
          muted:   '#8A8A8A',
          text:    '#F5F5F5',
          text2:   '#B8B8B8',
          // backward-compat
          black:   '#121212',
        },
        primary: {
          50:  '#FAFAFA',
          100: '#F5F5F5',
          200: '#E5E5E5',
          300: '#D4D4D4',
          400: '#B8B8B8',
          500: '#8A8A8A',
          600: '#5C5C5C',
          700: '#3D3D3D',
          800: '#2A2A2A',
          900: '#1A1A1A',
        },
      },
      animation: {
        'fade-in':    'fadeIn 0.6s ease-in-out',
        'fade-in-up': 'fadeInUp 0.7s ease-out',
        'slide-up':   'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-up':   'scaleUp 0.3s ease-out',
        'float':      'float 4s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow':  'spinSlow 12s linear infinite',
        'shimmer':    'shimmer 2s linear infinite',
        'marquee':    'marquee 24s linear infinite',
      },
      keyframes: {
        fadeIn:    { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp:  { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideUp:   { '0%': { transform: 'translateY(24px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideDown: { '0%': { transform: 'translateY(-20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        scaleUp:   { '0%': { transform: 'scale(0.94)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        float:     { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-12px)' } },
        shimmer:   { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        marquee:   { from: { transform: 'translateX(0%)' }, to: { transform: 'translateX(-50%)' } },
        spinSlow:  { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
      },
      backgroundImage: {
        'gradient-radial':   'radial-gradient(var(--tw-gradient-stops))',
        'gradient-silver':   'linear-gradient(135deg, #D4D4D4 0%, #8A8A8A 100%)',
        'gradient-dark':     'linear-gradient(135deg, #1A1A1A 0%, #121212 100%)',
        'gradient-luxury':   'linear-gradient(135deg, #2A2A2A 0%, #121212 100%)',
        'gradient-premium':  'linear-gradient(135deg, #D4D4D4 0%, #8A8A8A 100%)',
      },
      boxShadow: {
        'luxury':    '0 20px 48px -12px rgba(0,0,0,0.7), 0 4px 16px -4px rgba(0,0,0,0.5)',
        'luxury-lg': '0 32px 64px -12px rgba(0,0,0,0.9)',
        'silver':    '0 0 40px rgba(212,212,212,0.12)',
        'silver-lg': '0 0 60px rgba(212,212,212,0.2)',
        'premium':    '0 20px 48px -12px rgba(0,0,0,0.7)',
        'premium-lg': '0 32px 64px -12px rgba(0,0,0,0.9)',
        'inner-glow': 'inset 0 2px 4px 0 rgba(255,255,255,0.04)',
      },
      spacing: {
        '18':  '4.5rem',
        '88':  '22rem',
        '128': '32rem',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
    },
  },
  plugins: [],
}
